routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\HotelController;
use App\Http\Controllers\ComController;
use App\Http\Controllers\UserController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    #return view('welcome');
    return view('auth.login');
});

#Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/usercomment', [ComController::class,'user_comment'])->name('usercomment');
Route::get('/usercomment/{country}',[ComController::class,'user_comment']);
Route::delete('/usercomment/{country}/{id}/delete',[Comcontroller::class,'delete_comment']);
Route::post('/usercomment/{id}/{country}/edit',[Comcontroller::class,'update_comment']);

Route::get('/redirect',[HomeController::class,'redirect']);

Route::get('/search/result',[HotelController::class,'search']);

Route::get('/search/result/{country}/{hotel_id}/{location}/comment',[ComController::class,'hotel_comment']);
Route::post('/search/result/{country}/{hotel_id}/comment', [ComController::class,'store']);
//Route::get('/search/result/{country}/{hotel_id}/comment', [ComController::class,]);

// Route::get('/admin/manage_comment',[HotelController::class,'seeallcomment']);
// Route::get('/admin/manage_comment/{country}',[HotelController::class,'seeallcomment']);
// Route::get('/admin/manage_comment/{country}/search',[HotelController::class,'searchcomment']);

//管理員管理評論
#Route::get('/admin/comment/{country}',[ComController::class,'show']);//印出所有評論
Route::get('/admin/comment/{country}',[ComController::class,'user_comment']);//印出所有評論
Route::get('/admin/commentDelete/{country}/{id}',[ComController::class,'delete']);//刪除評論
Route::get('/admin/commentEdit/{country}/{id}',[ComController::class,'showData']);//印出要編輯的評論
Route::post('/admin/commentEdit/{country}/{id}',[ComController::class,'update']);//編輯評論

//管理員管理會員
Route::get('/admin/manage_member',[UserController::class,'show']);//印出所有會員
Route::get('/admin/userDelete/{id}',[UserController::class,'delete']);//刪除會員
Route::get('/admin/userEdit/{id}',[UserController::class,'showData']);//印出要編輯的會員
Route::post('/admin/userEdit',[UserController::class,'update']);//編輯會員

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/comment.blade.php
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">


<style>
.button {
  display: inline-block;
  border-radius: 4px;
  background-color: #F26419;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 16px;
  padding: 10px;
  width: 175px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -15px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}

.alert-danger{
  display:none;
}

</style>
<x-app-layout>
<title>查看其他使用者評論</title>    
<div id="header-wrapper">
    
    @if($country == 'jp')
        <div class="container p-3 my-3 text-white" style="background-color:#2F4858;width:500px;text-align:center;" >{{$hotel[0]->hotelname}} 的所有評論</div>
          @foreach ($comment as $com)
          <div class="container-sm p-3 border-4 border-dark border-top-0 border-bottom-0 border-right-0" style ="box-shadow: 4px 4px 8px 0 grey;background-color" >
          <div style="font-size:30px;">評論者 : {{$name_arr[$loop->index]}}</div>
          <div style="font-size:30px;">評論內容 : {{$com->content}}</div>
          <div style="font-size:30px;">飯店評分 : {{$com->rating}}</div>
          </div>
          <div class="container-sm p-3"></div>
          @endforeach
        
    @endif
    
    @if($country =='sg')
      <div class="container p-3 my-3 text-white" style="background-color:#2F4858;width:500px;text-align:center;" >{{$hotel[0]->hotelname}} 的所有評論</div>
        @foreach ($comment as $com)
        <div class="container-sm p-3 border-4 border-dark border-top-0 border-bottom-0 border-right-0" style ="box-shadow: 4px 4px 8px 0 grey;background-color" >
          <div style="font-size:30px;">評論者 : {{$user->name}}</div>
          <div style="font-size:30px;">評論內容 : {{$com->content}}</div>
          <div style="font-size:30px;">飯店評分 : {{$com->rating}}</div>
        </div>
        <div class="container-sm p-3"></div>
        @endforeach
    @endif
    <div class="container-sm p-3">
    <form action="{{ url('search/result/'.$country.'/'.$hotel[0]->hotel_id.'/comment') }}" method="POST" id="message-form-new">
        {{ csrf_field() }}
            
        <div style="padding-right: 50px " required="required">評論</div>           
        <textarea class="add_word" name='content' id="textarea" ></textarea>
        <div id='alert' class="alert alert-danger alert-dismissable">評論字數需小於50字</div> 
        
        <div style="padding-right: 50px " required="required">評分</div>
        <div>
            <input type="radio" name="rating" value="1" required>1
            <input type="radio" name="rating" value="2">2
            <input type="radio" name="rating" value="3">3
            <input type="radio" name="rating" value="4">4
            <input type="radio" name="rating" value="5">5   
        </div>   
        <div>
            <!--<input type="submit" value="送出" class="btn btn-primary" >-->
            <button  type="submit" class="btn btn-primary">確定</button>
        </div>  
    </form>
    </div>
    
    <div class="container-sm p-3">
    <a href="/search/result?country={{$country}}&search={{$location}}">
        <button class="button" style="vertical-align:middle"><span>返回查看其他飯店</span></button>  
    </a>
    </div>
</x-app-layout>

<script>
$(document).ready(function(){
  $('#textarea').bind('input propertychange', function() {
    if (this.value.length > 50) {
      $("#alert").show();
      $("#textarea").val($("#textarea").val().substring(0,50));
    }
    else{
      $("#alert").hide();
    }
  });
});

</script>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/map.blade.php
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>SJHotel日新飯店地圖</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet" />
<link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500' rel='stylesheet' type='text/css'>
<script src="http://maps.google.com/maps/api/js?key=AIzaSyDSN747FpZTAGiN4nbTbWCJQl0HeduVUTw" type="text/javascript"></script>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<style>
.button {
  display: inline-block;
  border-radius: 4px;
  background-color: #f4511e;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 28px;
  padding: 20px;
  width: 200px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}
.container {
  border: 10px solid #1d3557;
  padding: 10px;
  
}
.item {
  width:800px;
  padding: 5px; 
}
.container-sm span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.container-sm:hover span {
  padding-bottom: 15px;
  padding-right: 15px;
}

</style>

<x-app-layout>
<html> 
<!--<center>-->
<head> 
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" /> 
    <title>Google Maps Multiple Markers</title> 
    
</head>

<div class="container-sm p-3" id="header-wrapper"></div>

<body>
     
    @if (count($hotels) == 0) <!-- 資料庫查不到 -->
    <div style="font-size:50px;">{{$error_message}}</div>
    <form action="{{url('/redirect')}}" method="get">
        <button type="submit" class="button container-sm p-3" style="vertical-align:middle"><span>重新查詢 </span></button>        
    </form>
    @else <!-- 有找到 -->
    <div class="container" style="width: 1000px;">
      <div id="map" class="container-md p-3 " style="width: 750px; height: 400px;"></div>

      <div class="container-md p-3 "></div>
      <div class="item container-md p-3" id="side_bar" style="overflow:auto; height:450px"></div>
    </div>
    <form action="{{url('/redirect')}}" method="get">
        <button type="submit" class="button" style="margin-left: 600px;margin-right: 600px;"><span>重新查詢 </span></button>        
    </form>
    @endif

    <script type="text/javascript">
        var latlng = [];
        
        @foreach ($hotels as $hotel)
        latlng.push([{{$hotel->id}},'{{$hotel->hotelname}}',{{$hotel->latitude}},   //0,1,2
                    {{$hotel->longitude}},'{{$hotel->address}}','{{$hotel->url}}',  //3,4,5
                    {{$hotel->avg_rating}},{{$hotel->total_comments}}])             //6,7
        @endforeach
      
        var side_bar_html = "";  
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 11,
            center: new google.maps.LatLng(latlng[0][2],latlng[0][3]),
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });
        
        var infowindow = new google.maps.InfoWindow();
        var markers = []
        var marker, i;
        
        for (i = 0; i < latlng.length; i++) {  
            marker = new google.maps.Marker({
            position: new google.maps.LatLng(latlng[i][2], latlng[i][3]),
            map: map
            });
        
            google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
            infowindow.setContent(latlng[i][1]);
            infowindow.setContent('<span><div class="container-sm p-3 "><div style="background-color:#ee9b00"><strong>' + latlng[i][1] +
                          '</strong><br>' + '地址 : ' + latlng[i][4] + '</div>'+
                          '<div> 評分 : '+latlng[i][6]+'</div><div> 共'+latlng[i][7]+'則評論<div>'+
                          '<div><strong>飯店網站連結 : </strong><br>'+
                          '<a href='+latlng[i][5]+'>'+latlng[i][1]+'</a></div></span>');
            infowindow.open(map, marker);
            }
        })(marker, i));
        markers.push(marker)
        
 
        }
        
        var i = 0
        @foreach ($hotels as $hotel)
        side_bar_html +='<span><div id="info" class="container-md p-3 border-4 border-dark border-top-0 border-bottom-0 border-right-0 " style="box-shadow: 4px 4px 8px 0 grey;background-color:">'+
                        '<a href="javascript: myclick('+ (i) +')">' + 
                        '<p>飯店名稱 : '+'{{$hotel->hotelname}}'+'</p><p>飯店地址 : '+'{{$hotel->address}}'+
                        '</p><a href='+'{{$hotel->url}}'+'>點我查看飯店連結</a>' + 
                        '<div ><a href = {{ url('search/result/'.$country.'/'.$hotel->hotel_id.'/'.$location.'/comment') }}>點我查看會員評論</a></div>'+ 
                        '</a></div><div class="container-sm p-3"></div></span>';
        
        i+=1
        
        @endforeach             // url('search/'.$country.'/'.$site->id.'/message')
        document.getElementById("side_bar").innerHTML = side_bar_html


        function myclick(i) {
            // zoom to marker so added to map
            map.setCenter(markers[i].getPosition());
            map.setZoom(19);
            google.maps.event.trigger(markers[i], "click");
        }
    
        
    </script>
    <!--</center>-->
</body>
</html>

</x-app-layout>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/searchhotel.blade.php
<x-app-layout>
<html>
<style>
.button {
  display: inline-block;
  border-radius: 4px;
  background-color:#000000;
  border: none;
  color: #ffffff;
  text-align: center;
  font-size: 20px;
  padding: 20px;


  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}



.button:hover span:after {
  opacity: 1;
  right: 0;
}
</style>

<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <title></title>
</head>

<body>

<div id="header-wrapper">
    <center><div style="font-size:50px;">請先選擇查詢國家並輸入地區名稱</div>
    <div id="header" class="container ">
        <div id="logo" >
            <div style="font-size:30px;"<a href="#">SJ HOTEL日本新加坡飯店地圖</a></div>
            </center>
    </div>
    <br>


<center>
<table  style="width: 40%;">
<tr>
<td><img src="{{URL('images/jp.jpeg')}}" alt=""> </td>
<td><img src="{{URL('images/sg.jpeg')}}" alt=""></td>
</tr>
</table>

<br>
<td>
<form action="{{ url('search/result') }}" method="get" >
<input type="radio" style="border-radius:20px" name="country" value="jp" checked>日本
<input type="radio" style="border-radius:20px" name="country" value="sg">新加坡
<br>

<form action="{{url('/redirect')}}" method="get">
<input  style="border:4px black solid;" type="text" class="form-controller" placeholder="&nbsp&nbsp請輸入地區名稱"  id="search" name="search" required></input>

<button type="submit" class="button" style="vertical-align:middle"><span>查詢 </span></button>

    </form>
</td>
</tr>

</table>
</center>

</div>



</div>

</body>

</html>
</x-app-layout>

resources/views/show_user_comment.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<style>
.button {
  display: inline-block;
  border-radius: 4px;
  background-color: #F26419;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 16px;
  padding: 10px;
  width: 170px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}

.alert-danger{
  display:none;
}

div.card {
  width: 250px;
  box-shadow: 2px 2px 8px 0 grey;
  text-align: center;
}

div.header {
  background-color: #ee9b00;
  color: white;
  padding: 30px;
  font-size:40px;
}

.container-sm span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.container-sm:hover span {
  padding-bottom: 15px;
  padding-right: 15px;
}

</style>
<title>會員歷史評論</title>
<x-app-layout>
    <div class="container p-3 my-3 text-white" style="background-color:#2F4858">
    
      <a href = '/usercomment/jp'>
          <button class="button" style="vertical-align:middle"><span>查看日本評論</span></button>  
      </a>
      <a href = '/usercomment/sg'>
          <button class="button" style="vertical-align:middle "><span>查看新加坡評論</span></button>  
      </a>
    </div> 
    
    @foreach($hotelnames as $h)
    
    <div class="container-sm p-3 border-4 border-dark border-top-0 border-bottom-0 border-right-0 " style="box-shadow: 4px 4px 8px 0 grey;background-color:">
      <div class="row" >
        <div class="col-6" style="font-size:30px;">{{$h}}</div>
        
      </div>
      <div class="card">
        <div class="header">
          <div>{{$comments[$loop->index]->rating}}分</div>
        </div>
        <div class="container">
          <p>{{$comments[$loop->index]->content}}</p>
        </div>
        <span>
          <div class="container-sm p-3 ">
          <form action="{{ url('/usercomment/'.$country.'/'.$comments[$loop->index]->id.'/delete') }}" method="post">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="{{'#myModal'.$comments[$loop->index]->id}}" >編輯評論</button>
            {!! csrf_field() !!}
            {!! method_field('DELETE') !!}
            <button type="submit" class="btn btn-danger" data-bs-dismiss="modal" onClick="return confirm('確定要刪除嗎？');">刪除評論</button>
          </form>
          </div>
        </span>
      </div>
      
    </div>
    
    <!-- The Modal -->
    <div class="modal" id="{{'myModal'.$comments[$loop->index]->id}}">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

          <!-- Modal Header -->
          <div class = "modal-header">
            <div style="right:100px;"><button type="button" class="btn-close" data-bs-dismiss="modal" right= "150px"></button></div>
          </div>
          <!-- Modal body -->
          <div class="modal-body" align = "center">
            <div>請輸入新評論</div>
            <form action="{{ url('/usercomment/'.$comments[$loop->index]->id.'/'.$country.'/edit') }}" method="POST">
              {!! csrf_field() !!}  
              <input type="hidden" name = "id" value = "{{$comments[$loop->index]->id}}">
                <textarea class="add_word" name='content' id="textarea{{$comments[$loop->index]->id}}" required>{{$comments[$loop->index]->content}}</textarea>
                <div id='alert{{$comments[$loop->index]->id}}' class="alert alert-danger alert-dismissable">評論字數需小於50字</div>
                <div>
                  <input type="radio" name="rating" value="1" {{ ($comments[$loop->index]->rating==1)? "checked" : "" }} >1</label>
                  <input type="radio" name="rating" value="2" {{ ($comments[$loop->index]->rating==2)? "checked" : "" }} >2</label>
                  <input type="radio" name="rating" value="3" {{ ($comments[$loop->index]->rating==3)? "checked" : "" }} >3</label>
                  <input type="radio" name="rating" value="4" {{ ($comments[$loop->index]->rating==4)? "checked" : "" }} >4</label>
                  <input type="radio" name="rating" value="5" {{ ($comments[$loop->index]->rating==5)? "checked" : "" }} >5</label>
                </div>
                <div style = "padding:10px 15px;">
                  <button  type="submit" class="btn btn-primary" data-bs-dismiss="modal">確定</button>
                  <button  type="button" class="btn btn-danger" data-bs-dismiss="modal">取消</button>
                </div>
                
            </form>
          </div>
          
        </div>
      </div>
    </div>
    <div class="container-sm p-3"></div>
    @endforeach

</x-app-layout>   

<script>
$(document).ready(function(){
  
  @foreach($hotelnames as $h)
  $('#textarea{{$comments[$loop->index]->id}}').bind('input propertychange', function() {
      if (this.value.length > 50) {
        $("#alert{{$comments[$loop->index]->id}}").show();
        $("#textarea{{$comments[$loop->index]->id}}").val($("#textarea{{$comments[$loop->index]->id}}").val().substring(0,50));
      }
      else{
        $("#alert{{$comments[$loop->index]->id}}").hide();
      }
    });
  @endforeach
});


</script>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>